# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll

gems: [jekyll-paginate]

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://groovyghoul.github.io" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: bytemares - now with nudity

description: ranting of a sane person
author:
  name: richard
  email: richard@bytemares.com
  github: groovyghoul
  twitter: richard_oneil
  #pinterest: asd123
  #linkedin: asd123
  #bio: Your stylish, minimalist theme!
  email_md5: 931279b475440ddd113a5f92f6de18c7

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
